name: Run Gosec
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        GOPATH: /home/runner/work/k8s-collectorset-controller/
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: gover
        run: |
          go version && echo $GOPATH
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
